name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-java@v1.3.0
      with:
        java-version: 1.8
        
    - uses: jfrog/setup-jfrog-cli@v1.0.5
    
    - uses: actions/checkout@v2
      
    - run: mvn -B package
        
    - name: Release to GitHub
      run: |
        set -x
        assets=()
        for asset in target/*.{jar,deb,rpm}; do
          assets+=("-a" "$asset")
        done
        tag_name="${GITHUB_REF##*/}"
        
        hub release edit "${assets[@]}" -m "$tag_name" "$tag_name"
        
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Release to Bintray Debian Repo
      run: |
        deb_file="target/*.deb"
        deb_version=$(dpkg-deb --field ${deb_file} Version)
        
        target="instaclustr/debian/instaclustr-everywhere-strategy/${deb_version}"
        
        jfrog bt --key "${BINTRAY_API_KEY}" version-create "${target}"
        jfrog bt --key "${BINTRAY_API_KEY}" upload "${deb_file}" "${target}"
        
      env:
        BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
